#+title: External sort on Magnetic tape simulator
#+author: Давид Чередник

Implementation of an *external* multi-pass K-way merge sort with constrained RAM and sequential tape I/O interface.

The tape consists of contiguous ~int32_t~ cells stored in a binary file. All operations are sequential and random access is not assumed by the sorting algorithm. Temporary tape files may be created during execution to store intermediate sorted runs.

RAM constraint is strictly enforced: at no point does the algorithm exceed ~O(RAMCells)~ memory usage.

This implementation is intended as a correct simulation of external merge sort under RAM and sequential tape constraints. Performance optimisations and I/O efficiency weren't the primary objective.
* How to build

#+begin_src bash
cmake -S . -B build
cmake --build build
#+end_src

Note that linker may try to complain about the use of ~tmpnam~. This was an intentional choice, since there is no portable way to use ~FILE *~ descriptor returned by ~mkstemp~ or ~tmpfile~ with C++ file streams.
* How to run

#+begin_src bash
./build/tapesort [-?|-h|--help] <in.bin> <out.bin> [-c|--config <conf.toml>]
#+end_src

Example configuration (with default values):
#+begin_src toml
[sort]
ram = 100 # how many tape cells can be in the memory

[tape]
# delays are in milliseconds
read_delay = 10
write_delay = 20
move_delay = 5
#+end_src

A helper utility is provided to inspect tape contents in human-readable form:
#+begin_src bash
./build/filetape print <tape.bin>
#+end_src

Random test tapes can be generated using:
#+begin_src bash
dd if=/dev/urandom of=rand.bin bs=4 count=N
#+end_src
* Tests

Unit tests were not implemented. To compensate, a set of representative input cases is provided in ~example/~: each of the input must produce the correct output without any failures.

Different RAM limits were tested: for example, ~ram = size - 1~, ~ram = size~, ~ram = size + 1~ and ~ram = 10 * size~.
